### ISSUE TITLE
About CDA

### ISSUE THREAD

**Issue by JhuoW** [wyl7/ClusterSCL#2]
HI, 

I have some confusion about cluster-aware data augmentation. Second 4.2 says that distant positives should not be pulled together too close, while close negatives should not be pushed apart too far. It is easy to understand that $\alpha$ defined as Eq. (5) can weaken the pull strength between distant positives. 

However, if we want to weaken the push strength between close negatives, I think for close negatives, $\alpha$ should be small to guarantee they are not pushed too far. While for distant negatives, $\alpha$ should be large. So the principle of negative sample pairs should be different from positive pairs, but in the paper, they use the same principle. 

Sec 4.2 says “Considering that Eq. 3 explicitly models the pulling between each positive sample pair rather than the pushing between each negative sample pair, we design the principle of adjusting $\alpha$ from the perspective of positive sample pairs.” But the denominator of Eq. 3 also pushes the negatives.

**Comment by wyl7** [comment]
> HI,
> 
> I have some confusion about cluster-aware data augmentation. Second 4.2 says that distant positives should not be pulled together too close, while close negatives should not be pushed apart too far. It is easy to understand that α defined as Eq. (5) can weaken the pull strength between distant positives.
> 
> However, if we want to weaken the push strength between close negatives, I think for close negatives, α should be small to guarantee they are not pushed too far. While for distant negatives, α should be large. So the principle of negative sample pairs should be different from positive pairs, but in the paper, they use the same principle.
> 
> Sec 4.2 says “Considering that Eq. 3 explicitly models the pulling between each positive sample pair rather than the pushing between each negative sample pair, we design the principle of adjusting α from the perspective of positive sample pairs.” But the denominator of Eq. 3 also pushes the negatives.

Hello,

Thanks for your attention! 😄

In CDA, we use the same principle to treat positives and negatives because,

(1) Minimization of the contrastive loss is often regarded as the maximization of mutual information between anchor and its positives. The negatives randomly sampled are used to facilitate the computation of mutual information. From this perspective, we think the positive samples should be concerned more.

(2) If a negative sample is already far away from the anchor, we do not need to pay too much attention on a negative sample. Therefore, using a larger or smaller alpha is not important.

(3) If a negative sample is close to the anchor, we still assign a larger alpha to it. That is because if we assign a smaller alpha to it, we will indirectly treat the cluster center as our negative sample, which will harm the learning process.

Actually, more future work on the negative samples is worth further studying.

**Comment by wyl7** [comment]
> HI,
> 
> I have some confusion about cluster-aware data augmentation. Second 4.2 says that distant positives should not be pulled together too close, while close negatives should not be pushed apart too far. It is easy to understand that α defined as Eq. (5) can weaken the pull strength between distant positives.
> 
> However, if we want to weaken the push strength between close negatives, I think for close negatives, α should be small to guarantee they are not pushed too far. While for distant negatives, α should be large. So the principle of negative sample pairs should be different from positive pairs, but in the paper, they use the same principle.
> 
> Sec 4.2 says “Considering that Eq. 3 explicitly models the pulling between each positive sample pair rather than the pushing between each negative sample pair, we design the principle of adjusting α from the perspective of positive sample pairs.” But the denominator of Eq. 3 also pushes the negatives.

Hello,

Thanks for your attention! 😄

In CDA, we use the same principle to treat positives and negatives because,

(1) Minimization of the contrastive loss is often regarded as the maximization of mutual information between anchor and its positives. From this perspective, we think the positive samples should be concerned more.

(2) If a negative sample is already far away from the anchor, we do not need to pay too much attention on the negative sample. Therefore, using a larger or smaller alpha is not important.

(3) If a negative sample is close to the anchor, we still assign a larger alpha to it. That is because if we assign a smaller alpha to it, we will indirectly treat the cluster center as our negative sample, which will harm the learning process.

Actually, more future work on the negative samples is worth further studying.

**Comment by JhuoW** [comment]
Thanks for your explanation.
